name: Manual Service Testing

on:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service to run'
        required: true
        default: 'github_trending'
        type: choice
        options:
          - oricon_ranking
          - github_trending  
          - vocaloid_ranking
          - youtube_user
          - bilibili_user
      
      user_id:
        description: 'User ID (for YouTube/Bilibili services)'
        required: false
        default: ''
        type: string

jobs:
  test-service:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          
      - name: Install dependencies
        run: go mod tidy
        
      - name: Build binary
        run: go build -o main
        
      - name: Validate inputs
        run: |
          echo "Selected service: ${{ inputs.service }}"
          echo "User ID: ${{ inputs.user_id }}"
          
          # Note: User ID is now optional for user services due to default configuration
          if [[ "${{ inputs.service }}" == "youtube_user" || "${{ inputs.service }}" == "bilibili_user" ]]; then
            if [[ -z "${{ inputs.user_id }}" ]]; then
              echo "ℹ️  No User ID provided. Using default configuration."
              echo "Examples for custom User ID:"
              echo "  - YouTube: @MrBeast, UCX6OQ3DkcsbYNE6H8uQQuVA, or pewdiepie"
              echo "  - Bilibili: 1, 946974, or any numeric UID"
            else
              echo "📋 Using provided User ID: ${{ inputs.user_id }}"
            fi
          fi
        
      - name: Run Standard Services
        if: ${{ !contains(fromJson('["youtube_user", "bilibili_user"]'), inputs.service) }}
        run: |
          echo "🚀 Running service: ${{ inputs.service }}"
          ./main -task=${{ inputs.service }}
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          
      - name: Run YouTube User Service (with custom user ID)
        if: ${{ inputs.service == 'youtube_user' && inputs.user_id != '' }}
        run: |
          echo "🎬 Testing YouTube User Service with custom User ID..."
          echo "User ID: ${{ inputs.user_id }}"
          echo "Command: ./main -task=youtube_user -user-id='${{ inputs.user_id }}'"
          ./main -task=youtube_user -user-id="${{ inputs.user_id }}"
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          
      - name: Run YouTube User Service (with default configuration)
        if: ${{ inputs.service == 'youtube_user' && inputs.user_id == '' }}
        run: |
          echo "🎬 Testing YouTube User Service with default configuration..."
          echo "Command: ./main -task=youtube_user"
          ./main -task=youtube_user
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          YOUTUBE_DEFAULT_USER_ID: ${{ secrets.YOUTUBE_DEFAULT_USER_ID }}
          
      - name: Run Bilibili User Service (with custom UID)
        if: ${{ inputs.service == 'bilibili_user' && inputs.user_id != '' }}
        run: |
          echo "📺 Testing Bilibili User Service with custom UID..."
          echo "UID: ${{ inputs.user_id }}"
          echo "Command: ./main -task=bilibili_user -uid='${{ inputs.user_id }}'"
          ./main -task=bilibili_user -uid="${{ inputs.user_id }}"
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          
      - name: Run Bilibili User Service (with default configuration)
        if: ${{ inputs.service == 'bilibili_user' && inputs.user_id == '' }}
        run: |
          echo "📺 Testing Bilibili User Service with default configuration..."
          echo "Command: ./main -task=bilibili_user"
          ./main -task=bilibili_user
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_TEST_WEBHOOK_URL }}
          BILIBILI_DEFAULT_UID: ${{ secrets.BILIBILI_DEFAULT_UID }}
          
      - name: Service Test Complete
        run: |
          echo "✅ Service test completed successfully!"
          echo "Service: ${{ inputs.service }}"
          if [[ -n "${{ inputs.user_id }}" ]]; then
            echo "User ID: ${{ inputs.user_id }}"
          fi
          echo "Check the logs above for detailed output."
