name: Quick Service Tests (Presets)

on:
  workflow_dispatch:
    inputs:
      test_preset:
        description: 'Select a test preset'
        required: true
        type: choice
        default: 'all_standard'
        options:
          - all_standard
          - youtube_mrbeast
          - youtube_pewdiepie
          - bilibili_admin
          - bilibili_popular_up
          - custom_youtube
          - custom_bilibili
          
      custom_user_id:
        description: 'Custom User ID (only for custom_* presets)'
        required: false
        default: ''
        type: string

jobs:
  quick-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"
          
      - name: Install dependencies
        run: go mod tidy
        
      - name: Build binary
        run: go build -o main
        
      - name: Show test information
        run: |
          echo "🧪 Quick Test Preset: ${{ inputs.test_preset }}"
          echo "📋 Available presets:"
          echo "  - all_standard: Run all standard services (oricon, github, vocaloid)"
          echo "  - youtube_mrbeast: Test YouTube service with MrBeast channel"
          echo "  - youtube_pewdiepie: Test YouTube service with PewDiePie channel" 
          echo "  - bilibili_admin: Test Bilibili service with admin account (UID: 1)"
          echo "  - bilibili_popular_up: Test Bilibili service with popular uploader"
          echo "  - custom_youtube: Test YouTube with custom user ID"
          echo "  - custom_bilibili: Test Bilibili with custom UID"
          echo ""
        
      - name: Run All Standard Services
        if: ${{ inputs.test_preset == 'all_standard' }}
        run: |
          echo "🎵 Running Oricon Ranking..."
          ./main -task=oricon_ranking
          echo ""
          echo "⭐ Running GitHub Trending..."
          ./main -task=github_trending
          echo ""
          echo "🎤 Running Vocaloid Ranking..."
          ./main -task=vocaloid_ranking
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_CHAT_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_SYS_WEBHOOK_URL }}
          
      - name: Test YouTube - MrBeast
        if: ${{ inputs.test_preset == 'youtube_mrbeast' }}
        run: |
          echo "🎬 Testing YouTube with MrBeast (@MrBeast)"
          ./main -task=youtube_user -user-id="@MrBeast"
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_CHAT_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_SYS_WEBHOOK_URL }}
          
      - name: Test YouTube - PewDiePie
        if: ${{ inputs.test_preset == 'youtube_pewdiepie' }}
        run: |
          echo "🎬 Testing YouTube with PewDiePie (UCX6OQ3DkcsbYNE6H8uQQuVA)"
          ./main -task=youtube_user -user-id="UCX6OQ3DkcsbYNE6H8uQQuVA"
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_CHAT_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_SYS_WEBHOOK_URL }}
          
      - name: Test Bilibili - Admin Account
        if: ${{ inputs.test_preset == 'bilibili_admin' }}
        run: |
          echo "📺 Testing Bilibili with admin account (UID: 1)"
          ./main -task=bilibili_user -uid="1"
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_CHAT_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_SYS_WEBHOOK_URL }}
          
      - name: Test Bilibili - Popular UP
        if: ${{ inputs.test_preset == 'bilibili_popular_up' }}
        run: |
          echo "📺 Testing Bilibili with popular UP (UID: 946974)"
          ./main -task=bilibili_user -uid="946974"
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_CHAT_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_SYS_WEBHOOK_URL }}
          
      - name: Test Custom YouTube
        if: ${{ inputs.test_preset == 'custom_youtube' }}
        run: |
          if [[ -z "${{ inputs.custom_user_id }}" ]]; then
            echo "❌ Error: custom_user_id is required for custom_youtube preset"
            echo "Please provide a YouTube user ID like @username, UCxxxx, or username"
            exit 1
          fi
          echo "🎬 Testing YouTube with custom user: ${{ inputs.custom_user_id }}"
          ./main -task=youtube_user -user-id="${{ inputs.custom_user_id }}"
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_CHAT_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_SYS_WEBHOOK_URL }}
          
      - name: Test Custom Bilibili
        if: ${{ inputs.test_preset == 'custom_bilibili' }}
        run: |
          if [[ -z "${{ inputs.custom_user_id }}" ]]; then
            echo "❌ Error: custom_user_id is required for custom_bilibili preset"
            echo "Please provide a Bilibili UID (numeric)"
            exit 1
          fi
          echo "📺 Testing Bilibili with custom UID: ${{ inputs.custom_user_id }}"
          ./main -task=bilibili_user -uid="${{ inputs.custom_user_id }}"
        env:
          DISCORD_CHAT_WEBHOOK_URL: ${{ secrets.DISCORD_CHAT_WEBHOOK_URL }}
          DISCORD_SYS_WEBHOOK_URL: ${{ secrets.DISCORD_SYS_WEBHOOK_URL }}
          
      - name: Test Summary
        run: |
          echo "🎉 Quick test completed!"
          echo "Preset used: ${{ inputs.test_preset }}"
          if [[ "${{ inputs.test_preset }}" == "custom_youtube" || "${{ inputs.test_preset }}" == "custom_bilibili" ]]; then
            echo "Custom user ID: ${{ inputs.custom_user_id }}"
          fi
          echo ""
          echo "📊 Check the logs above for detailed results."
          echo "💬 If Discord webhook is configured, results should also appear in your Discord channel."
